version: '3.8'

networks:
  agr-dev:
    name: dev-agr

services:
  nginx:
    image: nginx:1.23.1-alpine
    container_name: agr-nginx
    restart: always
    ports:
      - "80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - agr-dev
      
  postgres:
    image: postgres:15-alpine
    container_name: agr-postgres
    restart: unless-stopped
    ports:
      - "7432:5432" # Cambia el puerto para evitar conflictos
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: agr_db
      POSTGRES_USER: agr_usuario
      POSTGRES_PASSWORD: agr_clave
      TZ: America/Guayaquil
    networks:
      - agr-dev

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agr-php
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - agr-dev

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: agr-gotenberg
    restart: unless-stopped
    networks:
      - agr-dev