version: '3.8'

networks:
  agr-dev:
    name: dev-agr

services:
  nginx:
    image: nginx:1.23.1-alpine
    container_name: agr-nginx
    restart: always
    ports:
      - "80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - agr-dev

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agr-php
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - agr-dev

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: agr-gotenberg
    restart: unless-stopped
    networks:
      - agr-dev